var langue = ({
    fr:{
        accueil : "Accueil" ,
        technique : "Technique",
        doc : "Documentation",
        climat : "Climat",
        region : "Region",
        carte : "Carte",
        plante : "Plantes",
        titre1 : "Sauvons le monde, ",
        titre2 : "par les Innovations téchniques",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Outils",
        onglet1_descritpion : "Des outils innovantes et dérnières génerations",
        onglet2 : "Outils",
        onglet2_descritpion : "Des outils innovantes et dérnières génerations",
        onglet3 : "Outils",
        onglet3_descritpion : "Des outils innovantes et dérnières génerations",
        onglet4 : "Outils",
        onglet4_descritpion : "Des outils innovantes et dérnières génerations",
        connaissance : "Avant-propos",
        mada : "Madagascar",
        description_connaissance :"Depuis quelques décennies, le changement climatique s’aggrave et présente des effets néfastes. Cela reflète sur les phénomènes météorologiques, l’épuisement des ressources naturelles et sur l’agriculture. Cette dernière menace le monde à l’égard de la pression démographique élevée. Environ 0,5% de terres arables à Madagascar sont disparues chaque année. Ce contexte incite la curiosité des jeunes développeurs et élève ingénieur agronome promoteurs de développement, à chercher des alternatives pour pouvoir éradiquer la destruction  de la nature.",
        description_technique : "Les techniques agricoles intelligentes face au climat peuvent augmenter la productivité agricole et les revenus, rendre les communautés rurales plus résilientes au changement climatique et, si possible, atténuer le changement climatique.",
        gallerie : 'GALLERIE',
        afficher_plus:'Afficher plus',
        tout:'Tout',
        contacter : "Contacter-nous" ,
        nom : "Nom",
        prenom : "Prenom",
        email : "Email" ,
        telephone : "Telephone",
        Objet : "Objet",
        message : "Message",
        envoyer : "Envoyer",
        liens : "Liens" ,
        a_propos : "A propos de nous",
        rechercher : "Rechercher",
        nous_contacter : "Nous contacter",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves.",
        list_technique :"Listes des techniques :",
        list_plante : "Listes des plantes :",
        list_region : "Listes des régions :",
        liste_climat : "Listes des climats :",
        description_region : "Lorem, ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur porro libero voluptate itaque similique totam quidem numquam quibusdam doloribus sit, mollitia dolorem, modi. Modi ut molestiae ipsum, adipisci aut quis!",
        titre_1_bloc :"Page 'Accueil' " ,
        sous_titre_1_bloc :"" ,
        description_1_bloc :"Dans la première page , vous pourriez appercevoir une barre de recherche qui vous aidera à  rechercher parmi nos téchniques selon les régions. Vous pourriez également nous envoyer directement un email , ou vianos contacts et réseaux sociaux en bas de la page." ,
        finalisation_1_bloc :"Si vous vouez devenir unde vulgarisateur , vous pourriez créer un compte , et vous pourriez aussi nous des nouvelles téchniques qu'on va encore vérifier." ,
        titre_2_bloc :"Page 'Téchnique'" ,
        sous_titre_2_bloc :"" ,
        description_2_bloc :"Dans cette page, il y aura la liste de toutes les téchnique qu'on a sur notre base de donées , bien sûr vous pourriez aussi proposer d'autre en créant un compte vulgarisateurs. Vous n'avez cliquer sur un des téchniques en savoir un peu plus comme les étapes, les matériels, et aussi des liens externes pour vous données plus d'infomration sur le téchnique en particulier." ,
        finalisation_2_bloc :"Pour vous faciliter la navigation sur le site,  vous pourriez directement taper sur la barrre des tâches." ,
        titre_3_bloc :"Page Carte" ,
        sous_titre_3_bloc :"" ,
        description_3_bloc :"Sur cette page , il y  aura une carte de Madagascar avec ses 22 régions sur les quelles on pourra aussi cliquer , qui nous redirigera directement sur les détails de la régions comme le type , la structure du sols , le climat qu'il y a , les plantes  qui s'adaptera parfaitement dans ce genre terrains mais surtout les téchnique à savoir pour no cultivateurs. " ,
        finalisation_3_bloc :"" ,
        titre_4_bloc :"Page plantes" ,
        sous_titre_4_bloc :"" ,
        description_4_bloc :"Dans cette page , vous pourriez consulter toutes les différentes plantes qui sont cultivés à Madagascar. Vous n'avez qu'à cliquer sur l'un d'eux pour en savoir plus d'informations, comme toutes les critères ses exigences pendant son stade phénologique lumière, température, humidité, on vous propose également les nouvelles téchniques AIC qui pourraient améliorer sa culture." ,
        finalisation_5_bloc :"" ,
        titre_5_bloc :"UN BONUS" ,
        sous_titre_5_bloc :" Comment devenir un 'Vulgarisateur' ?" ,
        description_5_bloc :"Comme les données " ,
        finalisation_5_bloc :"" ,
    },
    mg:{
        accueil : "Fandraisana" ,
        technique : "Teknika",
        region : "Faritra",
        mada : "Madagasikara",
        climat : "Toe-tany",
        carte : "Sari-tany", 
        doc : "Fampafantarana",
        plante : "Zava-maniry",
        titre1 : "Fambolena ho an'ny rehetra",
        titre2 : "Vokatra sy Teknika",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Fitaovana",
        onglet1_descritpion : "Fitaovana manaraka ny fenitra",
        onglet2 : "Fitaovana",
        onglet2_descritpion : "Fitaovana manaraka ny fenitra",
        onglet3 : "Fitaovana",
        onglet3_descritpion : "Fitaovana manaraka ny fenitra",
        onglet4 : "Fitaovana",
        onglet4_descritpion : "Fitaovana manaraka ny fenitra",
        connaissance : "Voalohany",
        description_connaissance :"Tao anatin'izay folo taona lasa izay dia niharatsy ny fiovan'ny toetrandro ary nisy fiatraikany ratsy. Hita taratra izany amin'ny fisehoan-toetr'andro, ny fihenan'ny harena voajanahary ary ny fambolena. Ity farany dia mandrahona izao tontolo izao amin'ny resaka tsindry hazon'ny mponina. Manodidina ny 0,5% ny tany azo volena eto Madagasikara no very isan-taona. Mampientanentana ny fahalianan'ny tanora mpamorona sy mpampiroborobo ny fampandrosoana ny injeniera momba ny fambolena ity toe-javatra ity, hikatsahana safidy hafa hahafahana mamongotra ny fanimbana ny natiora." ,
        gallerie : 'SARY',
        afficher_plus:'Manaraka',
        tout:'Rehetra',
        contacter : "Hiresaka aminay" ,
        nom : "Anarana",
        prenom : "Fanampin'anarana",
        email : "Mailaka" ,
        telephone : "Laharana finday",
        Objet : "Zavatra",
        message : "Hafatra",
        envoyer : "Alefa",
        liens : "Rohy" ,
        a_propos : "Mombamomba anay",
        rechercher : "Hitady",
        nous_contacter : "Hiresaka aminay",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves.",
        list_technique :"Lisitr'ireo techniques :",
        list_plante : "Lisitr'ireo zava-maniry :",
        list_region : "Lisitr'ireo faritra :",
        liste_climat : "Lisitr'ireo toe-tany :",
        description_region : "Lorem, ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur porro libero voluptate itaque similique totam quidem numquam quibusdam doloribus sit, mollitia dolorem, modi. Modi ut molestiae ipsum, adipisci aut quis!" ,
        titre_1_bloc :"Pejy 'FANDRAISANA'" ,
        sous_titre_1_bloc :"" ,
        description_1_bloc :"Ao amin'ny pejy FANDRAISANA dia afaka manao fitadiavana teknika na faritra amin'ny alalan'ny teny iray eo amin'ny saha 'Hitady'. Eo ambany dia misy santionana teknika izay afaka tsindrina dia mivoaka ny momba azy. Afaka manoratra ho aty aminay koa ianareo eo amin'ny saha 'Hiresaka aminay'" ,
        finalisation_1_bloc :"Eny amin'ny tongotry ny pejy dia ahitana ny momba anay toy ny laharan'tarombia, mailaka, tambazotra tserasera" ,
        titre_2_bloc :"Pejy TEKNIKA" ,
        sous_titre_2_bloc :"" ,
        description_2_bloc :"Ao amin'ny pejy TEKNIKA dia ahitana ireo lisitra teknika izay misy ao anatin'ny tranonkala tanimboly.org. Miseho eo alohan'ny sary ny lohatenin'ilay teknika ahafantarana azy mialoha. Ra hijery ny momban'ny teknika iray de tsindrina ilay teknika ka hisokatra manaraka izay ny momba azy" ,
        finalisation_2_bloc :"Misy saha fitadiavana ihany koa etsy ambonin'ireo lisitra ahafahana mitady teknika na faritra na zava-maniry na ireo rehetra ireo miaraka" ,
        titre_3_bloc :"Pejy SARI-TANY" ,
        sous_titre_3_bloc :"" ,
        description_3_bloc :"Ao amin'ny pejy SARI-TANY dia misy sarin'i Madagasikara ahitana ireo faritra 22 miaraka amin'ny endrik'izy reo tsirairay avy. Afaka manindry faritra iray ahitana ny momba azy sy ny tekinika, toe-tany ary zava-maniry mifandraika aminy. Afaka manoratra ny faritra tadiavina manokana koa eo amin'ny saha 'Hijery faritra' " ,
        finalisation_3_bloc :"" ,
        titre_4_bloc :"Pejy ZAVA-MANIRY" ,
        sous_titre_4_bloc :"" ,
        description_4_bloc :"Pejy ZAVA-MANIRY dia ahitana ireo lisitry ny zava-maniry misy ao amin'ny tranonkala tanimboly.org. Raha te hijery ny zava-maniry hafa dia tsindrio ny 'Manaraka'. Raha te hahita ny momban'ny zava-maniry iray dia tsindrio ny zava-maniry araka ny safidinao ka hisokatra manaraka izay ny momba azy" ,
        finalisation_5_bloc :"" ,
        titre_5_bloc :"Pejy TOE-TANY" ,
        sous_titre_5_bloc :"" ,
        description_5_bloc :"Ao amin'ny pejy TOE-TANY diaahitana ireo karazana toe-tany misy eto Madagasikara sy ireo momba azy tsirairay avy" ,
        finalisation_5_bloc :"" ,
    }
})
export default langue