var langue = ({
    fr:{
        accueil : "Accueil" ,
        technique : "Technique",
        doc : "Documentation",
        climat : "Climat",
        region : "Region",
        carte : "Carte",
        plante : "Plantes",
        titre1 : "Agricuture pour la vie",
        titre2 : "Produits et téchnique",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Outils",
        onglet1_descritpion : "Des outils innovantes et dérnières génerations",
        onglet2 : "Outils",
        onglet2_descritpion : "Des outils innovantes et dérnières génerations",
        onglet3 : "Outils",
        onglet3_descritpion : "Des outils innovantes et dérnières génerations",
        onglet4 : "Outils",
        onglet4_descritpion : "Des outils innovantes et dérnières génerations",
        connaissance : "Connaissance",
        mada : "Madagascar",
        description_connaissance :"Depuis quelques décennies, le changement climatique s’aggrave et présente des effets néfastes. Cela reflète sur les phénomènes météorologiques, l’épuisement des ressources naturelles et sur l’agriculture. Cette dernière menace le monde à l’égard de la pression démographique élevée. Environ 0,5% de terres arables à Madagascar sont disparues chaque année. Ce contexte incite la curiosité des jeunes développeurs et élève ingénieur agronome promoteurs de développement, à chercher des alternatives pour pouvoir éradiquer la destruction  de la nature.",
        description_technique : "Les techniques agricoles intelligentes face au climat peuvent augmenter la productivité agricole et les revenus, rendre les communautés rurales plus résilientes au changement climatique et, si possible, atténuer le changement climatique.",
        gallerie : 'GALLERIE',
        afficher_plus:'Afficher plus',
        tout:'Tout',
        contacter : "Contacter-nous" ,
        nom : "Nom",
        prenom : "Prenom",
        email : "Email" ,
        telephone : "Telephone",
        Objet : "Objet",
        message : "Message",
        envoyer : "Envoyer",
        liens : "Liens" ,
        a_propos : "A propos de nous",
        rechercher : "Rechercher",
        nous_contacter : "Nous contacter",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves.",
        list_technique :"Listes des techniques :",
        list_plante : "Listes des plantes :",
        list_region : "Listes des régions :",
        liste_climat : "Listes des climats :",
        description_region : "Lorem, ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur porro libero voluptate itaque similique totam quidem numquam quibusdam doloribus sit, mollitia dolorem, modi. Modi ut molestiae ipsum, adipisci aut quis!",
        about_us:"Français"
    },
    mg:{
        accueil : "Fandraisana" ,
        technique : "Teknika",
        region : "Faritra",
        mada : "Madagasikara",
        climat : "Toe-tany",
        carte : "Sari-tany", 
        doc : "Fampafantarana",
        plante : "Zava-maniry",
        titre1 : "Fambolena ho an'ny rehetra",
        titre2 : "Vokatra sy Teknika",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Fitaovana",
        onglet1_descritpion : "Fitaovana manaraka ny fenitra",
        onglet2 : "Fitaovana",
        onglet2_descritpion : "Fitaovana manaraka ny fenitra",
        onglet3 : "Fitaovana",
        onglet3_descritpion : "Fitaovana manaraka ny fenitra",
        onglet4 : "Fitaovana",
        onglet4_descritpion : "Fitaovana manaraka ny fenitra",
        connaissance : "Fahaizana",
        description_connaissance :"Tao anatin'izay folo taona lasa izay dia niharatsy ny fiovan'ny toetrandro ary nisy fiatraikany ratsy. Hita taratra izany amin'ny fisehoan-toetr'andro, ny fihenan'ny harena voajanahary ary ny fambolena. Ity farany dia mandrahona izao tontolo izao amin'ny resaka tsindry hazon'ny mponina. Manodidina ny 0,5% ny tany azo volena eto Madagasikara no very isan-taona. Mampientanentana ny fahalianan'ny tanora mpamorona sy mpampiroborobo ny fampandrosoana ny injeniera momba ny fambolena ity toe-javatra ity, hikatsahana safidy hafa hahafahana mamongotra ny fanimbana ny natiora." ,
        gallerie : 'SARY',
        afficher_plus:'Manaraka',
        tout:'Rehetra',
        contacter : "Hiresaka aminay" ,
        nom : "Anarana",
        prenom : "Fanampin'anarana",
        email : "Mailaka" ,
        telephone : "Laharana finday",
        Objet : "Zavatra",
        message : "Hafatra",
        envoyer : "Alefa",
        liens : "Rohy" ,
        a_propos : "Mombamomba anay",
        rechercher : "Hitady",
        nous_contacter : "Hiresaka aminay",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves.",
        list_technique :"Lisitr'ireo techniques :",
        list_plante : "Lisitr'ireo zava-maniry :",
        list_region : "Lisitr'ireo faritra :",
        liste_climat : "Lisitr'ireo toe-tany :",
        description_region : "Lorem, ipsum dolor sit, amet consectetur adipisicing elit. Aspernatur porro libero voluptate itaque similique totam quidem numquam quibusdam doloribus sit, mollitia dolorem, modi. Modi ut molestiae ipsum, adipisci aut quis!" ,
        about_us:"Malagasy"
    }
})
export default langue