var data = ({
    fr:{
        accueil : "ACCUEIL" ,
        technique : "TECHNIQUE",
        climat : "CLIMAT",
        carte : "CARTE",
        plante : "PLANTES",
        titre1 : "Agricuture pour la vie",
        titre2 : "Produits et téchnique",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Outils",
        onglet1_descritpion : "Des outils innovantes et dérnières génerations",
        onglet2 : "Outils",
        onglet2_descritpion : "Des outils innovantes et dérnières génerations",
        onglet3 : "Outils",
        onglet3_descritpion : "Des outils innovantes et dérnières génerations",
        onglet4 : "Outils",
        onglet4_descritpion : "Des outils innovantes et dérnières génerations",
        connaissance : "Connaissance",
        description_connaissance :"La sécurité alimentaire et le  changement climatique peuvent être abordés ensemble en transformant l'agriculture et en adoptant des pratiques",
        description_technique : "Les techniques agricoles intelligentes face au climat peuvent augmenter la productivité agricole et les revenus, rendre les communautés rurales plus résilientes au changement climatique et, si possible, atténuer le changement climatique.",
        gallerie : 'GALLERIE',
        contacter : "Contacter-nous" ,
        nom : "Nom",
        prenom : "Prenom",
        email : "Email" ,
        telephone : "Telephone",
        Objet : "Objet",
        message : "Message",
        envoyer : "Envoyer",
        liens : "Liens" ,
        a_propos : "A propos de nous",
        rechercher : "Rechercher",
        nous_contacter : "Nous contacter",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves."
    },
    mg:{
        accueil : "TONGASOA" ,
        technique : "TEKNIKA",
        climat : "TOE-TANY",
        carte : "SARY",
        plante : "ZAVA-MANIRY",
        titre1 : "Fambolena ho an'ny rehetra",
        titre2 : "Vokatra sy Teknika",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Fitaovana",
        onglet1_descritpion : "Fitaovana manaraka ny fenitra",
        onglet2 : "Fitaovana",
        onglet2_descritpion : "Fitaovana manaraka ny fenitra",
        onglet3 : "Fitaovana",
        onglet3_descritpion : "Fitaovana manaraka ny fenitra",
        onglet4 : "Fitaovana",
        onglet4_descritpion : "Fitaovana manaraka ny fenitra",
        connaissance : "Fahaizana",
        description_connaissance :"Ny filaminana ara-tsakafo sy ny fiovan'ny toetrandro dia azo iaraha-miaina amin'ny fanovana ny fambolena sy ny fampiharana fomba fanao",
        description_technique : "Ny teknikan'ny fambolena sy fihenan-tsaina amin'ny toetrandro dia afaka mampitombo ny vokatra sy ny fidiram-bolan'ny fambolena, mahatonga ny vondrom-piarahamonina ambanivohitra mahazaka kokoa ny fiovan'ny toetr'andro ary, raha azo atao, dia manalefaka ny fiovan'ny toetr'andro.",
        gallerie : 'SARY',
        contacter : "Hiresaka aminay" ,
        nom : "Anarana",
        prenom : "Fanampin'anarana",
        email : "Mailaka" ,
        telephone : "Laharana finday",
        Objet : "Zavatra",
        message : "Hafatr",
        envoyer : "Alefa",
        liens : "Rohy" ,
        a_propos : "Mombamoba anay",
        rechercher : "Hitady",
        nous_contacter : "Hiresaka aminay",
        copyright : "Copyright © 2021 Tanimboly. Tout droits réserves."
    }
})